### ISSUE TITLE
bitmap.Find no longer finds images

### ISSUE THREAD

**Issue by SirRFI** [vcaesar/bitmap#1]
- bitmap version (or commit ref): `v0.10.0-beta3.1`
- Go version: `go version go1.17.6 windows/amd64`
- Gcc version: `gcc.exe (x86_64-win32-seh-rev0, Built by MinGW-W64 project) 8.1.0` (recommended by robotgo's README)
- Operating system and bit: `Windows 10 64bit`
- Provide example code: 
```go
package main

import (
	"fmt"
	"github.com/go-vgo/robotgo"
	"github.com/vcaesar/bitmap"
)

func main() {
	haystack := robotgo.CaptureScreen(100, 0, 1000, 500)
	needle := robotgo.CaptureScreen(400, 200, 500, 300) // smaller than the one above
	x, y := bitmap.Find(needle, haystack, 0.1)
	fmt.Println(x, y)

	err := bitmap.Save(haystack, "haystack.bmp")
	if err != nil {
		log.Fatalf("saving haystack failed: %s", err)
	}
	err = bitmap.Save(needle, "needle.bmp")
	if err != nil {
		log.Fatalf("saving needle failed: %s", err)
	}

	haystackImg := bitmap.Open("haystack.bmp")
	needleImg := bitmap.Open("needle.bmp")
	x, y = bitmap.Find(needleImg, haystackImg, 0.1)
	fmt.Println(x, y)
}
```

## Description

In [another issue](https://github.com/go-vgo/robotgo/issues/461#issuecomment-1034224670) I noticed that `bitmap.Find` has problems finding images in newer versions than `bitmap@v0.10.0-beta2`. My initial tests were opening an image to search for from file system (png image) and search it on current screen. To narrow the problem down, I used `robotgo.CaptureScreen` to get both the "needle" (image to search for) and "haystack" (source image to search in). The results are consistent, and increasing tolerance/precision of the `Find` function does not help.

```
go get github.com/go-vgo/robotgo@v1.0.0-beta3 github.com/vcaesar/bitmap@v0.10.0-beta2 | go run .
300 200
300 200

go get github.com/go-vgo/robotgo@v1.0.0-beta4.1 github.com/vcaesar/bitmap@v0.10.0-beta3 | go run .
0 0
0 0

go get github.com/go-vgo/robotgo@v1.0.0-beta5 github.com/vcaesar/bitmap@v0.10.0-beta3.1 | go run .
0 0
0 0
```

Ps. Issue template asks for `gcv` version - I think `bitmap` was meant to be there.

**Comment by vcaesar** [comment]
Fixed by new robotgo.

**Comment by ooing** [comment]
May I ask how you compile a bitmap  
thank
